branches:
  - main
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/github'
  - ['@semantic-release/npm', { pkgRoot: './infrastructure' }]
  - ['@semantic-release/exec', { successCmd: 'echo "version=${nextRelease.version}" >> $GITHUB_OUTPUT' }]