name: Main Pushed
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install semantic-release
        run: npm install -g semantic-release
      - name: Release
        run: npx semantic-release
      - name: Publish Infrastructure
        working-directory: ./infrastructure
        run: npx semantic-release -- --branches main --plugins @semantic-release/npm