name: Main Pushed
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Build Application
        working-directory: ./application
        run: npm ci && npx ng build --output-path=dist/
      - name: Build Infrastructure
        working-directory: ./infrastructure
        run: npm ci && npm run build
      - name: Install semantic-release
        run: npm install -g semantic-release
      - name: Release
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
      - name: Upload Artifacts
        working-directory: ./application
        if: startsWith(steps.release.outputs.version, 'v')
        env:
          VERSION: ${{ steps.release.outputs.version }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ARTIFACTS_BUCKET: ${{ secrets.AWS_ARTIFACTS_BUCKET }}
        run: |
          (cd dist/ && zip -r ../application-${VERSION}.zip .)
          aws s3 mv application-${VERSION}.zip $AWS_ARTIFACTS_BUCKET